// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function EnrollMasqueKey(arg1:main.WarpAccount,arg2:string):Promise<main.MasqueAccount>;

export function ExportWireGuardZip(arg1:string):Promise<string>;

export function GenerateConfigs(arg1:string,arg2:number,arg3:number):Promise<{[key: string]: string}>;

export function RegisterCloudflareAccount(arg1:string,arg2:string):Promise<main.WarpAccount>;

export function RunWarpScoutFullEngine(arg1:number):Promise<Array<main.EndpointResult>>;
