// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EnrollMasqueKey(arg1, arg2) {
  return window['go']['main']['App']['EnrollMasqueKey'](arg1, arg2);
}

export function ExportWireGuardZip(arg1) {
  return window['go']['main']['App']['ExportWireGuardZip'](arg1);
}

export function GenerateConfigs(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateConfigs'](arg1, arg2, arg3);
}

export function RegisterCloudflareAccount(arg1, arg2) {
  return window['go']['main']['App']['RegisterCloudflareAccount'](arg1, arg2);
}

export function RunWarpScoutFullEngine(arg1) {
  return window['go']['main']['App']['RunWarpScoutFullEngine'](arg1);
}
